apiVersion: v1
kind: Pod
metadata:
  name: guestbook-ui
  labels:
    app: guestbook-ui
spec:
  containers:
    - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
      imagePullPolicy: IfNotPresent
      name: guestbook-ui
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
  restartPolicy: Always